### ISSUE TITLE
Open files failing on Mac OS 12 Beta

### ISSUE THREAD

**Issue by Gubbledenut** [rsre/K40-Whisperer-macOS#18] opened 2021-08-27 10:40 UTC
K40 Whisperer opens fine, but when I try to open a file I get window , 
<img width="328" alt="Screen Shot 2021-08-27 at 20 35 44" src="https://user-images.githubusercontent.com/77911907/131114738-e76c047f-6631-4c32-9bc6-e1cdeaaad665.png">
"The operation file open failed"
Seems like a realtivly simple file access issue?
Thanks

**Comment by rsre** [comment] 2021-08-27 11:58
Hi Gubbledenut,

What macOS version are you running?

**Comment by Gubbledenut** [comment] 2021-08-27 12:09
Gidday Ricardo,
I’m stupidly running the next Mac OS 12 beta... it's only the second app
that doesn't work in it..I am getting around it running k40 in a windows
emulation on fusion.
Thanks
David


Sent from my iPad

On 27 Aug 2021, at 21:59, Ricardo ***@***.***> wrote:

﻿

Hi Gubbledenut,

What macOS version are you running?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsre/K40-Whisperer-macOS/issues/18#issuecomment-907148423>,
or unsubscribe

**Comment by rsre** [comment] 2021-08-27 12:12
Alright,

I don't have any machines running macOS 12 beta, I'll set a VM and see if I can reproduce the problem.

Have a nice day

**Comment by rsre** [comment] 2021-09-01 07:17
I've been unable to create and boot a macOS 12 Beta VM. I'll try a few more things but if it doesn't work I'll have to wait until it comes out of beta and I can install it and boot.

**Comment by Gubbledenut** [comment] 2021-09-01 07:48
Thanks for trying, I will keep trying each time a new beta version comes
out...currently it's working fine in vmware fusion win10 ....meerkat works,
but it's too much, far prefer whisperer.
David

**Comment by tychop** [comment] 2021-10-27 15:09
Same issue here.... "The open file operation failed to connect to the open and save panel service."
Running "macOS Monterey version 12.0.1 (21A559)"

 I gave the application Full Disc access in system preferences, but to no avail....
 
 After pressing 'OK' the file open window gets closed and I'm left without an option to load a file.

<img width="1440" alt="Screenshot 2021-10-27 at 17 09 09" src="https://user-images.githubusercontent.com/80199/139093967-6fdb889c-c916-4b26-9205-0c369c52a89a.png">

**Comment by tychop** [comment] 2021-10-28 08:34
Just tested the two previous releases as well. They also give this same problem.
So It's probably indeed a macOS 12.x.x compatibility problem...

**Comment by rsre** [comment] 2021-10-28 08:42
Now that macOS Monterrey is out of beta I'll try again to run it inside a VM and see if I can make a build that fixes it.

**Comment by Gubbledenut** [comment] 2021-10-28 08:56
Thank you, I have reported it to Apple feedback as well during the beta testing.

**Comment by rsre** [comment] 2021-11-03 16:43
Alright, I managed to install macOS 12 Monterrey on Parallels and do some tests.

I installed all the build tools and tried to make a build. After some fighting with pyenv and zsh I managed to complete the build. However, the problem still happens.

I've been looking around and found this issue: https://github.com/corpnewt/ProperTree/issues/111

The problems, like usual, come from tkinter. I'll try later to build using the Python version recommended in that issue.

**Comment by rsre** [comment] 2021-11-03 17:03
I managed to install that Python version and complete a build that opens files on macOS Monterrey.
<img width="1136" alt="Screenshot 2021-11-03 at 18 00 50" src="https://user-images.githubusercontent.com/12608029/140121330-ffe7134e-bbf5-46fa-b9ac-30d778553f79.png">

For some reason the style of the buttons changes, but the file opening operation works.

When I have some more time I'll make some more tests and then a release for you guys.

**Comment by rsre** [comment] 2021-11-03 17:09
Finally decided just to throw the build here in case any of you wants to give it a try.

You can find it here: https://github.com/rsre/K40-Whisperer-macOS/releases/tag/v0.58.B

It seems to be working on Monterrey with all the updates as well as on Mojave.

**Comment by tychop** [comment] 2021-11-03 17:20
Looks like it's working.
Thanks!

**Comment by rsre** [comment] 2021-11-03 17:28
Awesome! I'll close this issue then.

Enjoy it :)

**Closed as completed by rsre** 2021-11-03 17:28 UTC

**Comment by Gubbledenut** [comment] 2021-11-03 20:12
Legend, thank you
